[theme]
primaryColor = "#FF1E26"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#1F1F1F"
font = "sans serif"

[client]
showErrorDetails = false
toolbarMode = "minimal"
showSidebarNavigation = true

[logger]
level = "info"

[server]
port = 8501
headless = true
runOnSave = true
maxUploadSize = 200
enableXsrfProtection = true
enableCORS = true

[browser]
gatherUsageStats = false
serverAddress = "localhost"

[runner]
magicEnabled = true
fastReruns = true
